export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAIL = 'GET_WEATHER_FAIL'

export const GET_WEATHERS_SUCCESS = 'GET_WEATHERS_SUCCESS'
export const GET_WEASTHER_FAIL = 'GET_WEATHERS_FAIL'

export const SHOW_ICON_LOCATION = 'SHOW_ICON_LOCATION'
export const HIDE_ICON_LOCATION = 'HIDE_ICON_LOCATION'
